/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    content: ContentBlock;
    mediaBlock: MediaBlock;
    archive: ArchiveBlock;
    formBlock: FormBlock;
    hero_one: HeroOneBlock;
    hero_two: HeroTwoBlock;
    hero_three: HeroThreeBlock;
    hero_four: HeroFourBlock;
    hero_five: HeroFiveBlock;
    about_us: AboutUsBlock;
    about_us_two: AboutUsTwoBlock;
    about_us_three: AboutUsThreeBlock;
    about_us_four: AboutUsFourBlock;
    counters: CountersBlock;
    counters_two: CountersTwoBlock;
    services: ServicesBlock;
    services_two: ServicesTwoBlock;
    services_three: ServicesThreeBlock;
    services_four: ServicesFourBlock;
    call_to_action: CallToActionBlock;
    team_block: TeamBlock;
    call_to_action_2: CallToAction2Block;
    subscribe: SubscribeBlock;
    portfolio: PortfolioBlock;
    portfolio_two: PortfolioTwoBlock;
    prices_block: PricesBlock;
    prices_two: PricesTwoBlock;
    intro: IntroBlock;
    portfolio_grid: PortfolioGrid;
    about_project: AboutProjectBlock;
    about_service: AboutServiceBlock;
    features: FeaturesBlock;
    features_two: FeaturesTwoBlock;
    faq: FaqBlock;
    reusable_block: ReusableBlock;
    about_team: AboutTeamBlock;
    testimonials: TestimonialsBlock;
    steps_block: StepsBlock;
    contact_form_block: ContactFormBlock;
    clients_block: ClientsBlock;
    career_block: CareerBlock;
    support_grid_block: SupportGridBlock;
    commitment_block: CommitmentBlock;
    staffing_services_block: StaffingServicesBlock;
    it_services_block: ITServicesBlock;
    industries_block: IndustriesBlock;
    why_partner_block: WhyPartnerBlock;
    about_us_premium_block: AboutUsPremiumBlock;
    core_services_block: CoreServicesBlock;
    premium_overview_block: PremiumOverviewBlock;
  };
  collections: {
    pages: Page;
    posts: Post;
    projects: Project;
    services: Service;
    team: Team;
    media: Media;
    categories: Category;
    users: User;
    'reusable-content': ReusableContent;
    clients: Client;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'reusable-content': ReusableContentSelect<false> | ReusableContentSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    blog: Blog;
    services_page: ServicesPage;
    projects_page: ProjectsPage;
    team_page: TeamPage;
    general: General;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    services_page: ServicesPageSelect<false> | ServicesPageSelect<true>;
    projects_page: ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    team_page: TeamPageSelect<false> | TeamPageSelect<true>;
    general: GeneralSelect<false> | GeneralSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  title?: string | null;
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  dividerTop?: boolean | null;
  dividerBottom?: boolean | null;
  padding_top?: ('0' | '160') | null;
  padding_bottom?: ('0' | '40' | '100' | '130' | '145' | '160') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        avatar?: (string | null) | Media;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  avatar?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  badge?: string | null;
  title?: string | null;
  contact_items?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  social_links?:
    | {
        icon_class?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  desc_title?: string | null;
  desc_content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  form_title?: string | null;
  form: string | Form;
  gmap_title?: string | null;
  gmap?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroOneBlock".
 */
export interface HeroOneBlock {
  bgImage?: (string | null) | Media;
  icon?: (string | null) | Media;
  subtitle?: string | null;
  title_line1?: string | null;
  title_line2?: string | null;
  title_line3?: string | null;
  description?: string | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  counter1_upper?: string | null;
  counter1_lower?: string | null;
  counter1_value?: string | null;
  counter2_upper?: string | null;
  counter2_lower?: string | null;
  counter2_value?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero_one';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroTwoBlock".
 */
export interface HeroTwoBlock {
  title?: string | null;
  users?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  bgImage?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero_two';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroThreeBlock".
 */
export interface HeroThreeBlock {
  video?: (string | null) | Media;
  title?: string | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  description?: string | null;
  users?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero_three';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroFourBlock".
 */
export interface HeroFourBlock {
  icon?: (string | null) | Media;
  subtitle?: string | null;
  title?: string | null;
  description?: string | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  bgImage?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero_four';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroFiveBlock".
 */
export interface HeroFiveBlock {
  icon?: (string | null) | Media;
  subtitle?: string | null;
  slides?:
    | {
        bgImage: string | Media;
        title: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero_five';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUsBlock".
 */
export interface AboutUsBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  portrait?: (string | null) | Media;
  founder_name?: string | null;
  founder_role?: string | null;
  founder_quote?: string | null;
  youtube_video_link?: string | null;
  image?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about_us';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUsTwoBlock".
 */
export interface AboutUsTwoBlock {
  badge?: string | null;
  title?: string | null;
  left_description?: string | null;
  counter_value?: string | null;
  counter_suffix?: string | null;
  counter_title?: string | null;
  right_description1?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  right_description2?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  timeline?:
    | {
        period?: string | null;
        head_title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  right_description3?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about_us_two';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUsThreeBlock".
 */
export interface AboutUsThreeBlock {
  badge?: string | null;
  title?: string | null;
  left_description?: string | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  right_description1?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  youtube_video_link?: string | null;
  image?: (string | null) | Media;
  right_description2?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  skills?:
    | {
        name?: string | null;
        percentage?: string | null;
        id?: string | null;
      }[]
    | null;
  right_description3?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  vision_mission_goals?:
    | {
        title?: string | null;
        description?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about_us_three';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUsFourBlock".
 */
export interface AboutUsFourBlock {
  icon?: (string | null) | Media;
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  users?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  image?: (string | null) | Media;
  counters?:
    | {
        upper?: string | null;
        lower?: string | null;
        value?: string | null;
        suffix?: string | null;
        /**
         * For styling; defaults based on index
         */
        suffix_class?: string | null;
        id?: string | null;
      }[]
    | null;
  partners?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about_us_four';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CountersBlock".
 */
export interface CountersBlock {
  counters?:
    | {
        value: string;
        suffix?: string | null;
        /**
         * Optional CSS class for suffix styling
         */
        suffix_class?: string | null;
        title: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  image?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'counters';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CountersTwoBlock".
 */
export interface CountersTwoBlock {
  counters?:
    | {
        value: string;
        suffix?: string | null;
        /**
         * Optional CSS class for suffix styling
         */
        suffix_class?: string | null;
        title: string;
        description?: string | null;
        bgImage?: (string | null) | Media;
        card_style?: ('mil-gray-card' | 'mil-angle-gray') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'counters_two';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  services?:
    | {
        title?: string | null;
        description?: string | null;
        image?: (string | null) | Media;
        icon?: (string | null) | Media;
        button_text?: string | null;
        button_url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesTwoBlock".
 */
export interface ServicesTwoBlock {
  badge?: string | null;
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  services?:
    | {
        title?: string | null;
        description?: string | null;
        list?:
          | {
              item?: string | null;
              id?: string | null;
            }[]
          | null;
        button_text?: string | null;
        button_url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services_two';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesThreeBlock".
 */
export interface ServicesThreeBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  services?:
    | {
        image?: (string | null) | Media;
        title?: string | null;
        description?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services_three';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesFourBlock".
 */
export interface ServicesFourBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  bgImage?: (string | null) | Media;
  services?:
    | {
        image?: (string | null) | Media;
        icon?: (string | null) | Media;
        title?: string | null;
        description?: string | null;
        url?: string | null;
        button_text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services_four';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  bgImage?: (string | null) | Media;
  icon?: (string | null) | Media;
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'call_to_action';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock".
 */
export interface TeamBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'team' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'team';
        value: string | Team;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'team_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  title: string;
  short?: string | null;
  social_links?: {
    facebook?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    email?: string | null;
  };
  layout: (ReusableBlock | ContentBlock | MediaBlock | IntroBlock | AboutTeamBlock)[];
  relatedTeam?: (string | Team)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  order?: number | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReusableBlock".
 */
export interface ReusableBlock {
  reusableContent: string | ReusableContent;
  customId?: string | null;
  bg_style?: ('default' | 'gray') | null;
  padding_top?: ('0' | '10') | null;
  padding_bottom?: ('0' | '5' | '6' | '8' | '10') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reusable_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-content".
 */
export interface ReusableContent {
  id: string;
  title: string;
  layout: (
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | HeroOneBlock
    | HeroTwoBlock
    | HeroThreeBlock
    | HeroFourBlock
    | HeroFiveBlock
    | AboutUsBlock
    | AboutUsTwoBlock
    | AboutUsThreeBlock
    | AboutUsFourBlock
    | CountersBlock
    | CountersTwoBlock
    | ServicesBlock
    | ServicesTwoBlock
    | ServicesThreeBlock
    | ServicesFourBlock
    | CallToActionBlock
    | TeamBlock
    | CallToAction2Block
    | SubscribeBlock
    | PortfolioBlock
    | PortfolioTwoBlock
    | PricesBlock
    | PricesTwoBlock
    | IntroBlock
    | PortfolioGrid
    | AboutProjectBlock
    | AboutServiceBlock
    | AboutTeamBlock
    | FeaturesBlock
    | FeaturesTwoBlock
    | FaqBlock
    | TestimonialsBlock
    | StepsBlock
    | ContactFormBlock
    | ClientsBlock
    | CareerBlock
    | SupportGridBlock
    | CommitmentBlock
    | StaffingServicesBlock
    | ITServicesBlock
    | IndustriesBlock
    | WhyPartnerBlock
    | AboutUsPremiumBlock
    | CoreServicesBlock
    | PremiumOverviewBlock
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToAction2Block".
 */
export interface CallToAction2Block {
  bgImage?: (string | null) | Media;
  title?: string | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'call_to_action_2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SubscribeBlock".
 */
export interface SubscribeBlock {
  title?: string | null;
  media_file?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'subscribe';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioBlock".
 */
export interface PortfolioBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button_label?: string | null;
  button_link?: string | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'projects' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'projects';
        value: string | Project;
      }[]
    | null;
  info?: string | null;
  more_label?: string | null;
  more_link?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolio';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  tag?: string | null;
  short_description?: string | null;
  price?: string | null;
  layout: (ReusableBlock | ContentBlock | MediaBlock | CallToActionBlock | IntroBlock | AboutProjectBlock)[];
  relatedProjects?: (string | Project)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  order?: number | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroBlock".
 */
export interface IntroBlock {
  bgImage?: (string | null) | Media;
  short_title?: string | null;
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'intro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutProjectBlock".
 */
export interface AboutProjectBlock {
  badge?: string | null;
  title?: string | null;
  info_items?:
    | {
        label?: string | null;
        value?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  intro_title?: string | null;
  intro_description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  approach_title?: string | null;
  approach_description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  delivered_title?: string | null;
  delivered_items?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  goals_title?: string | null;
  goals_items?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  results_title?: string | null;
  results_items?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  conclusion_title?: string | null;
  conclusion_description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about_project';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioTwoBlock".
 */
export interface PortfolioTwoBlock {
  badge?: string | null;
  title?: string | null;
  counter_value?: string | null;
  counter_suffix?: string | null;
  counter_title?: string | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'projects' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'projects';
        value: string | Project;
      }[]
    | null;
  info?: string | null;
  more_label?: string | null;
  more_link?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolio_two';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricesBlock".
 */
export interface PricesBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  plans?:
    | {
        name?: string | null;
        price?: string | null;
        price_suffix?: string | null;
        description?: string | null;
        features?:
          | {
              item?: string | null;
              disabled?: boolean | null;
              id?: string | null;
            }[]
          | null;
        button_text?: string | null;
        button_url?: string | null;
        button_style?: ('mil-light' | 'mil-accent' | 'mil-soft' | 'mil-dark') | null;
        card_style?: ('' | 'mil-gray-card' | 'mil-angle-gray') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prices_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricesTwoBlock".
 */
export interface PricesTwoBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  plans?:
    | {
        name?: string | null;
        price?: string | null;
        price_suffix?: string | null;
        description?: string | null;
        bgImage?: (string | null) | Media;
        card_style?: ('mil-gray-card' | 'mil-angle-gray') | null;
        button_style?: ('mil-light' | 'mil-accent' | 'mil-soft') | null;
        button_text?: string | null;
        button_url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'prices_two';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioGrid".
 */
export interface PortfolioGrid {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'projects' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'projects';
        value: string | Project;
      }[]
    | null;
  columns?: ('3' | '2' | '4') | null;
  container?: ('fluid' | 'boxed') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolio_grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutServiceBlock".
 */
export interface AboutServiceBlock {
  badge?: string | null;
  title?: string | null;
  intro_text?: string | null;
  counter_value?: string | null;
  counter_suffix?: string | null;
  counter_label?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  right_title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  process_title?: string | null;
  process_steps?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  deliverables_title?: string | null;
  deliverables?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about_service';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutTeamBlock".
 */
export interface AboutTeamBlock {
  portrait: string | Media;
  name: string;
  position?: string | null;
  contact_items?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  social_links?:
    | {
        icon_class?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  intro_description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  quote?: string | null;
  bio_description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  skills?:
    | {
        name?: string | null;
        percentage?: string | null;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        date?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  certificate_image?: (string | null) | Media;
  closing_description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about_team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock".
 */
export interface FeaturesBlock {
  badge?: string | null;
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  features?:
    | {
        icon?: (string | null) | Media;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesTwoBlock".
 */
export interface FeaturesTwoBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  features?:
    | {
        icon?: (string | null) | Media;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features_two';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  button1_text?: string | null;
  button1_url?: string | null;
  button2_text?: string | null;
  button2_url?: string | null;
  faqs?:
    | {
        question: string;
        answer?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  gray_bg_position?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  testimonials?:
    | {
        text: string;
        authorName: string;
        authorRole?: string | null;
        authorAvatar?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  subtitle?: string | null;
  title?: string | null;
  steps?:
    | {
        step_number: string;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  bottom_text_before_link?: string | null;
  bottom_link_label?: string | null;
  bottom_link_url?: string | null;
  bottom_text_after_link?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  image?: (string | null) | Media;
  map_iframe?: string | null;
  contact_cards?:
    | {
        title?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  subtitle?: string | null;
  title?: string | null;
  form: string | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact_form_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientsBlock".
 */
export interface ClientsBlock {
  subtitle?: string | null;
  title?: string | null;
  clients?: (string | Client)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'clients_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  name: string;
  logo: string | Media;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CareerBlock".
 */
export interface CareerBlock {
  image?: (string | null) | Media;
  title?: string | null;
  description?: string | null;
  button_text?: string | null;
  button_url?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'career_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SupportGridBlock".
 */
export interface SupportGridBlock {
  title?: string | null;
  items?:
    | {
        icon?: (string | null) | Media;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'support_grid_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommitmentBlock".
 */
export interface CommitmentBlock {
  title?: string | null;
  description?: string | null;
  image_alignment?: ('left' | 'right') | null;
  button_text?: string | null;
  button_url?: string | null;
  image?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'commitment_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StaffingServicesBlock".
 */
export interface StaffingServicesBlock {
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  services_title?: string | null;
  services?:
    | {
        icon?: (string | null) | Media;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'staffing_services_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ITServicesBlock".
 */
export interface ITServicesBlock {
  title?: string | null;
  services?:
    | {
        icon?: (string | null) | Media;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'it_services_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IndustriesBlock".
 */
export interface IndustriesBlock {
  title?: string | null;
  industries?:
    | {
        icon?: (string | null) | Media;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'industries_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyPartnerBlock".
 */
export interface WhyPartnerBlock {
  title?: string | null;
  background_image?: (string | null) | Media;
  features?:
    | {
        icon?: (string | null) | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'why_partner_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUsPremiumBlock".
 */
export interface AboutUsPremiumBlock {
  badge?: string | null;
  title?: string | null;
  description_1?: string | null;
  description_2?: string | null;
  image_back?: (string | null) | Media;
  image_front?: (string | null) | Media;
  award_icon?: (string | null) | Media;
  award_text?: string | null;
  tabs?:
    | {
        tab_title?: string | null;
        tab_description?: string | null;
        list_items?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  phone_text?: string | null;
  phone_number?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about_us_premium_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoreServicesBlock".
 */
export interface CoreServicesBlock {
  title?: string | null;
  description?: string | null;
  services_list?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'core_services_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PremiumOverviewBlock".
 */
export interface PremiumOverviewBlock {
  vision_title?: string | null;
  vision_text?: string | null;
  why_choose_title?: string | null;
  why_choose_list?:
    | {
        point?: string | null;
        id?: string | null;
      }[]
    | null;
  clients_title?: string | null;
  clients_description?: string | null;
  clients_list?:
    | {
        client_name?: string | null;
        id?: string | null;
      }[]
    | null;
  cta_title?: string | null;
  cta_description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'premium_overview_block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  layout: (
    | ReusableBlock
    | ContentBlock
    | MediaBlock
    | IntroBlock
    | StepsBlock
    | ContactFormBlock
    | ClientsBlock
    | CareerBlock
    | SupportGridBlock
    | CommitmentBlock
    | StaffingServicesBlock
    | ITServicesBlock
    | IndustriesBlock
    | WhyPartnerBlock
    | AboutUsPremiumBlock
    | CoreServicesBlock
    | PremiumOverviewBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * Override the default header style for this page.
   */
  headerStyle?: ('default' | 'dark' | 'invert') | null;
  /**
   * Override the default footer layout for this page.
   */
  footerLayout?: ('default' | 'minimal') | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  short?: string | null;
  list?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  layout: (ReusableBlock | ContentBlock | MediaBlock | IntroBlock | AboutServiceBlock)[];
  relatedServices?: (string | Service)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  order?: number | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'team';
          value: string | Team;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'reusable-content';
        value: string | ReusableContent;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?: T | {};
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  headerStyle?: T;
  footerLayout?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        avatar?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  short_description?: T;
  price?: T;
  layout?: T | {};
  relatedProjects?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  order?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  short?: T;
  list?:
    | T
    | {
        text?: T;
        id?: T;
      };
  layout?: T | {};
  relatedServices?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  order?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  title?: T;
  short?: T;
  social_links?:
    | T
    | {
        facebook?: T;
        linkedin?: T;
        instagram?: T;
        twitter?: T;
        email?: T;
      };
  layout?: T | {};
  relatedTeam?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  order?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-content_select".
 */
export interface ReusableContentSelect<T extends boolean = true> {
  title?: T;
  layout?: T | {};
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo?: {
    type?: ('image' | 'text') | null;
    logo?: (string | null) | Media;
    logo_invert?: (string | null) | Media;
    alt?: string | null;
    fontawesome_icon?: string | null;
    text?: string | null;
    link?: string | null;
  };
  contact?: {
    actionType?: ('link' | 'popup') | null;
    label?: string | null;
    fontawesome_icon?: string | null;
    link?: string | null;
    popupTitle?: string | null;
    popupItems?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    formTitle?: string | null;
    form?: (string | null) | Form;
  };
  ordercall?: {
    actionType?: ('link' | 'popup') | null;
    link?: string | null;
    formTitle?: string | null;
    form?: (string | null) | Form;
    bgImage?: (string | null) | Media;
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null)
            | ({
                relationTo: 'services';
                value: string | Service;
              } | null)
            | ({
                relationTo: 'team';
                value: string | Team;
              } | null);
          url?: string | null;
          label: string;
          submenu?:
            | {
                sub_type?: ('reference' | 'custom') | null;
                sub_newTab?: boolean | null;
                sub_reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null)
                  | ({
                      relationTo: 'projects';
                      value: string | Project;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: string | Service;
                    } | null)
                  | ({
                      relationTo: 'team';
                      value: string | Team;
                    } | null);
                sub_url?: string | null;
                label: string;
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Default header style. Can be overridden per page.
   */
  headerStyle?: ('default' | 'invert') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Choose footer layout used site-wide. Pages can override this.
   */
  layoutType?: ('default' | 'minimal') | null;
  logo: string | Media;
  logoLight?: (string | null) | Media;
  newsletter?: {
    placeholder?: string | null;
    buttonIcon?: string | null;
  };
  mainMenu?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  backgroundImage?: (string | null) | Media;
  policyLinks?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        icon: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  locations?:
    | {
        title: string;
        address: string;
        phone: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  createdBy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  layout_before?: ReusableBlock[] | null;
  layout_after?: ReusableBlock[] | null;
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  post_layout_after?: ReusableBlock[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_page".
 */
export interface ServicesPage {
  id: string;
  layout_before?: ReusableBlock[] | null;
  layout_after?: ReusableBlock[] | null;
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_page".
 */
export interface ProjectsPage {
  id: string;
  layout_before?: ReusableBlock[] | null;
  layout_after?: ReusableBlock[] | null;
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_page".
 */
export interface TeamPage {
  id: string;
  layout_before?: ReusableBlock[] | null;
  layout_after?: ReusableBlock[] | null;
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general".
 */
export interface General {
  id: string;
  not_found?: {
    bgImage?: (string | null) | Media;
    subtitle?: string | null;
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        type?: T;
        logo?: T;
        logo_invert?: T;
        alt?: T;
        fontawesome_icon?: T;
        text?: T;
        link?: T;
      };
  contact?:
    | T
    | {
        actionType?: T;
        label?: T;
        fontawesome_icon?: T;
        link?: T;
        popupTitle?: T;
        popupItems?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        formTitle?: T;
        form?: T;
      };
  ordercall?:
    | T
    | {
        actionType?: T;
        link?: T;
        formTitle?: T;
        form?: T;
        bgImage?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              submenu?:
                | T
                | {
                    sub_type?: T;
                    sub_newTab?: T;
                    sub_reference?: T;
                    sub_url?: T;
                    label?: T;
                    id?: T;
                  };
            };
        id?: T;
      };
  headerStyle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  layoutType?: T;
  logo?: T;
  logoLight?: T;
  newsletter?:
    | T
    | {
        placeholder?: T;
        buttonIcon?: T;
      };
  mainMenu?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  backgroundImage?: T;
  policyLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  social?:
    | T
    | {
        icon?: T;
        link?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  locations?:
    | T
    | {
        title?: T;
        address?: T;
        phone?: T;
        id?: T;
      };
  copyright?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  layout_before?: T | {};
  layout_after?: T | {};
  badge?: T;
  title?: T;
  description?: T;
  post_layout_after?: T | {};
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  layout_before?: T | {};
  layout_after?: T | {};
  badge?: T;
  title?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  layout_before?: T | {};
  layout_after?: T | {};
  badge?: T;
  title?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_page_select".
 */
export interface TeamPageSelect<T extends boolean = true> {
  layout_before?: T | {};
  layout_after?: T | {};
  badge?: T;
  title?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general_select".
 */
export interface GeneralSelect<T extends boolean = true> {
  not_found?:
    | T
    | {
        bgImage?: T;
        subtitle?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'team';
          value: string | Team;
        } | null)
      | ({
          relationTo: 'reusable-content';
          value: string | ReusableContent;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}